#
# Miner Willy Strikes Back Again
# Copyleft (C) 19941998 Mark-André Hopf
#
#-----------------------------------------------------------------------------

PRGFILE	= game

SRCS        = main.cc 

LIBS 	    =
LIBDIRS	    = 
INCDIRS	    = -I.

CLEAN =

# DEFINES = -D_REENTRANT -D__TOAD_THREADS

include ../../conf/MakefilePrg

# DO NOT DELETE

