#
# TOAD -- A Simple and Powerful C++ GUI Toolkit for the X Window System
# Copyright (C) 1996-2003 by Mark-André Hopf <mhopf@mark13.de>
#

PRGFILE		= colordialog
SRCS		= colordialog.cc

include ../../conf/MakefilePrg
