#
#
#-----------------------------------------------------------------------------

PRGFILE		= program

SRCS        = MainWindow.cc

LIBS		=

CLEAN       =

DEFINES		=


include ../../../conf/MakefilePrg
