############################################################################
#                                                                          #
# TOAD - thing on a desk                                                   #
# Copyright (C) 1996-2003 by Mark-André Hopf <mhopf@mark13.de>             #
#                                                                          #
############################################################################

PRGFILE		= combobox

SRCS		= combobox.cc

include ../../conf/MakefilePrg
