#
# TOAD -- A Simple and Powerful C++ GUI Toolkit for the X Window System
# Copyright (C) 1996-2000 by Mark-André Hopf <mhopf@mark13.org>
#

PRGFILE		= form
SRCS		= form.cc

include ../../conf/MakefilePrg
