############################################################################
#                                                                          #
# TOAD - thing on a desk                                                   #
# (C)opyright 1999 by Mark-André Hopf                                      #
#                                                                          #
############################################################################

PRGFILE		= timer

SRCS		= timer.cc

include ../../conf/MakefilePrg
