#
# TOAD -- A Simple and Powerful C++ GUI Toolkit for the X Window System    #
# Copyright (C) 1996-2000 by Mark-André Hopf                               #
#
#-----------------------------------------------------------------------------

PRGFILE		= program

SRCS        = MainWindow.cc

LIBS		=

CLEAN       =

DEFINES		=


include ../../../conf/MakefilePrg
