#
# Fischland -- A 2d vector graphics editor
# Copyright (C) 1999-2007 by Mark-André Hopf <mhopf@mark13.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307,  USA
#
#-----------------------------------------------------------------------------

PRGFILE		= fischland
SRCS		= draw.cc page.cc toolbox.cc lineal.cc fitcurve.cc \
                  colorpalette.cc fontdialog.cc cairo.cc \
		  fpath.cc selectiontool.cc directselectiontool.cc \
		  filltool.cc pentool.cc penciltool.cc
CLEAN		= resource.cc
# CFLAGS		= -I/usr/X11/include/cairo
LIBS		= -lXrender -lcairo

include ../../conf/MakefilePrg
