############################################################################
#                                                                          #
# TOAD -- A Simple and Powerful C++ GUI Toolkit for the X Window System    #
# Copyright (C) 1996-2000 by Mark-André Hopf                               #
#                                                                          #
############################################################################

PRGFILE		= doubleclick
SRCS		= doubleclick.cc

include ../../conf/MakefilePrg
