#
# TOAD -- A Simple and Powerful C++ GUI Toolkit
# Copyright (C) 1995-2003 by Mark-André Hopf <mhopf@mark13.de>
#

PRGFILE		=	font
SRCS			= font.cc
# LIBS    = -lefence

include ../../conf/MakefilePrg
