############################################################################
#                                                                          #
# TOAD -- A Simple and Powerful C++ GUI Toolkit for the X Window System    #
# Copyright (C) 1996-2010 by Mark-André Hopf <mhopf@mark13.org>            #
#                                                                          #
############################################################################


PRGFILE		= robot
SRCS		= robot.cc glwindow.cc

# LIBS		= -lXext -lMesaGL -lMesaGLU -lm
LIBS		= -lGL -lm
INCDIRS		=
LIBDIRS		=

include ../../conf/MakefilePrg
